version: '3'
services:
  env:
    image: "golang:1.16"
    environment:
      - ENV=dev
      - GCP_PROJECT_ID=suzuito-minilla
      - GCP_BUCKET_ARTICLE=suzuito-minilla-blog1-article
      - GOOGLE_APPLICATION_CREDENTIALS=./suzuito-minilla-9b66c0d5d334.json
      # pubsub emulator
      - PUBSUB_EMULATOR_HOST=gcp:8432
      - PUBSUB_EMULATOR_HOST=fastalert-dummy
    working_dir: /opt/app
    volumes:
      - .:/opt/app
    links:
      - gcp:gcp
    depends_on:
      - gcp
    command: /bin/sh -c 'sleep infinity'
    ports:
      - 8080:8080
  gcp:
    image: google/cloud-sdk:emulators
    command: gcloud beta emulators pubsub start --project=fastalert-dummy
    ports:
      - 8085:8085 # pubsub
